services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "8000:6379"
  tournament:
    build: ./tournier/
    ports:
      - "5000:5000"
    depends_on:
      - redis